WebService/API/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('status/', views.statusView, name='status'),
	path('status/<str:node>/', views.nodeStatusView, name='nodeStatus'),
	path('addComment/<int:photoId>', views.addComment, name='addComment'),
	path('addGalleryComment/<int:galleryId>', views.addGalleryComment, name='addGalleryComment'),
	path('deleteComment/<int:commentId>/', views.deleteComment, name='deleteComment'),
	path('uploadPhoto/', views.uploadPhoto, name='uploadPhoto'),
	path('uploadProfilePhoto/', views.uploadProfilePhoto, name='uploadProfilePhoto'),
	path('makeFriendship/<int:friendId>/', views.makeFriendship, name='makeFriendship'),
	path('deleteFriendship/<int:friendId>/', views.deleteFriendship, name='deleteFriendship'),
	path('login', views.loginExternal, name='login'),
	path('register', views.registerExternal, name='register'),
	path('likePhoto/<int:photoId>/', views.likePhoto, name='likePhoto'),
	path('deletePhoto', views.deletePhoto, name='deletePhoto'),
	path('deleteGallery/<int:galleryId>/', views.deleteGallery, name='deleteGallery'),
	path('profile', views.profile, name='profile'),
	path('gallery', views.gallery, name='gallery'),
	path('homeFeed', views.homeFeed, name='homeFeed'),
	path('galleryFeed', views.galleryFeed, name='galleryFeed'),
]

WebService/WebService/urls.py
from django.contrib import admin
from django.urls import path, include

from WebService.zoo import zk

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include(('App.urls', 'App'), namespace='App')),
	path('api/', include(('API.urls', 'API'), namespace='API')),
]
zk.initialize()

WebService/App/models.py
import json
import requests
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from WebService.cryptography import cr
from WebService.zoo import zk


class Gallery(models.Model):
	Owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
	Name = models.CharField(max_length=100)

	def __str__(self): return str(self.Name) + " - " + str(self.Owner)


class Photo(models.Model):
	Gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, default=1, null=True, blank=True)
	UploadDateTime = models.DateTimeField(auto_now_add=True, null=True)
	UUID = models.CharField(max_length=1024)
	Location = models.CharField(default='', blank=True, null=True, max_length=100)
	Description = models.CharField(default='', blank=True, null=True, max_length=1024)

	def __str__(self): return str(self.Gallery) + " - " + self.UUID

	@property
	def url(self):
		try:
			requestUrl = zk.applicationService + 'getStorageService/' + self.UUID + '/'
			response = requests.get(requestUrl)
			content = json.loads(response.text)
			try:
				username = self.Gallery.Owner.username
			except Exception:
				username = ""
			sharedKeyBase64 = ''
			for storageService in zk.storageServicesList:
				if storageService['url'] == content['storageService']:
					sharedKeyBase64 = storageService['sharedKey']
					break
			hmac = cr.defaultEncrypt(inputData=self.UUID + username, sharedKeyBase64=sharedKeyBase64)['data']
			url = content['storageService'] + 'getImage?uuid=' + self.UUID + '&username=' + username + '&hmac=' + hmac
			return url
		except Exception:
			return ""


class Profile(models.Model):
	User = models.OneToOneField(User, on_delete=models.CASCADE)
	AuthService = models.CharField(max_length=100, blank=True, default='')
	AuthServiceUserId = models.PositiveIntegerField(blank=True, default=1)
	ProfilePhoto = models.ForeignKey(Photo, on_delete=models.SET_DEFAULT, default=None, null=True, blank=True)

	@property
	def FullName(self): return self.User.first_name + ' ' + self.User.last_name

	def __str__(self): return self.FullName

	@property
	def photoUrl(self):
		try:
			requestUrl = zk.applicationService + 'getStorageService/' + self.PhotoUUID + '/'
			response = requests.get(requestUrl)
			content = json.loads(response.text)
			return content['storageService'] + 'getImage/' + self.PhotoUUID + '/'
		except Exception:
			return ""


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(User=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()


class Friendship(models.Model):
	User = models.ForeignKey('auth.User', default=1, on_delete=models.CASCADE, related_name='User')
	Friend = models.ForeignKey('auth.User', default=1, on_delete=models.CASCADE, related_name='Friend')

	def __str__(self): return str(self.User) + " -> " + str(self.Friend)


class GalleryComment(models.Model):
	User = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
	Gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, default=1)
	UploadDateTime = models.DateTimeField(default=None, null=True)
	Text = models.CharField(max_length=1024)

	def __str__(self): return str(self.Gallery) + " - " + str(self.UploadDateTime)


class PhotoComment(models.Model):
	User = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
	Photo = models.ForeignKey(Photo, on_delete=models.CASCADE, default=1)
	UploadDateTime = models.DateTimeField(auto_now_add=True, null=True)
	Text = models.CharField(max_length=1024)

	def __str__(self): return str(self.Photo) + " - " + str(self.UploadDateTime)


class Like(models.Model):
	User = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
	Photo = models.ForeignKey(Photo, on_delete=models.CASCADE, default=1)

	def __str__(self): return str(User) + " - " + str(Photo)

WebService/templates/Shared/dividerTitle.html
<div class="container h-100">
	<div class="row justify-content-center align-items-center" style="height: 200px">
		<div class="col">
			<h1 class="text-center ">{{ title }}</h1>
			<hr class="hr-black">
		</div>
	</div>
</div>

WebService/templates/Shared/dynamicPhotoCard.html
<a :name="[[ photo.uuid ]]"></a>
<div class="navbar-placeholder"></div>
<div class="container align-content-center">
	<div class="col-xl-6 col-lg-8 col-md-10 mx-auto">
		<div class="card">
			<div class="card-header bg-white">
				<div class="row align-items-center px-2">
					<a href="">
						<img style="height: 36px; width: 36px; border-radius: 100%"
						     :src="[[ photo.profilePhotoUrl ]]">
					</a>
					<div class="ml-2">
						<a class="m-0 text-dark" :href="'{% url 'API:profile' %}?id='+[[ photo.ownerId ]]"><strong>[[ photo.ownerFullName ]]</strong></a>
						<br>
						<a class="text-dark" href="#">[[ photo.location ]]</a>
					</div>
					<div class="dropdown ml-auto">
						<h6 class="m-0" data-toggle="dropdown">
							<i class="fas fa-ellipsis-h"></i>
						</h6>
						<div class="dropdown-menu">
							<a class="dropdown-item" :href="'{% url 'API:deletePhoto' %}?id='+[[ photo.id ]]">
								Delete Image
								<i class="far fa-trash-alt"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="card-body p-0">
				{#										<a href="{% url 'App:gallery' photo.galleryId %}#[[ photo.UUID ]]">#}
				<a :href="'{% url 'API:gallery' %}?id=' + [[ photo.galleryId ]] + '#' + [[ photo.uuid ]]">
					<img class="card-img" :src="[[ photo.url ]]" alt="">
				</a>
			</div>
			<div class="card-footer bg-white">
				<div class="row align-items-center px-2">
					<a class="text-dark mr-3" @click="likePhoto(photo.id)">
						<h4>
							<i :id="'heart' + [[ photo.id ]]" :class="[photo.isLiked==1 ? 'fas fa-heart text-danger' : 'far fa-heart']"></i>
							{# Todo: Check if already liked#}
							{# <i class="fas fa-heart"></i>#}
						</h4>
					</a>
					<a class="text-dark" href="#">
						<h4>
							<i class="far fa-comment"></i>
						</h4>
					</a>
					<a class="ml-auto text-dark" href="#">
						<h4>
							<i class="far fa-bookmark"></i>
							{# Todo: Change icon when pressed#}
							{# <i class="fas fa-bookmark"></i>#}
						</h4>
					</a>
				</div>
				<div class="row px-2">
					<a class="text-dark mr-2" href="#">
						<strong :id="'likesCounter' + [[ photo.id ]]">[[ photo.likesCounter ]]</strong><strong> likes</strong>
					</a>
				</div>
				<div v-if="photo.description" class="row px-2">
					<a class="text-dark mr-1" :href="'{% url 'API:profile' %}?id=' + [[ photo.ownerId ]]"><strong>[[ photo.ownerFullName ]]</strong></a>
					<span>[[ photo.description ]]</span>
				</div>
				{# <div class="row px-2">#}
				{#      <a class="text-secondary mr-2" href="#">View all 22 comments</a>#}
				{# </div>#}
				<div class="row px-2">
					<ul class="d-block p-0 m-0" style="list-style: none">
						<li v-for="comment in photo.comments" :id="'comment' + [[ comment.id ]]">
							<a class="text-dark mr-1" :href="'{% url 'API:profile' %}?id=' + [[ comment.userId ]]"><strong>[[ comment.userFullName ]]</strong></a>
							<span>[[ comment.text ]]</span>
							<a v-if="comment.canDelete" class="text-dark" @click="deleteComment(comment.id)"><i class="far fa-trash-alt"></i></a>
						</li>
					</ul>
				</div>
				<div class="row px-2">
					<a class="text-secondary mr-2" href="#">
						<time :datetime="[[ photo.UploadDateTime ]]">[[ photo.uploadDateTime ]]</time>
					</a>
				</div>
				<hr>
				<div class="row px-2">
					<form :id="'form' + [[ photo.id]] " class="form-inline w-100" action="#" @submit.prevent="addComment(photo.id)">
						{# <form class="form-inline w-100" method="get" action="{% url 'API:addComment' photo.id %}">#}
						<div class="input-group w-100">
							<input :id="'photoTextInput' + [[ photo.id ]]" type="text" name="comment" class="form-control" style="resize: none" aria-label="Add a comment…" placeholder="Add a comment…">
							<div class="input-group-append">
								<button class="btn btn-outline-dark input-group-text" type="submit">
									<i class="far fa-comment"></i>
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

WebService/templates/Shared/galleryCard.html
<a name="{{ gallery.id }}"></a>
<div class="navbar-placeholder"></div>
<div class="container align-content-center">
	<div class="col-xl-6 col-lg-8 col-md-10 mx-auto">
		<div class="card">
			<div class="card-header bg-white">
				<div class="row align-items-center px-2">
					<div class="ml-2">
						<a class="text-dark" href="{% url 'App:gallery' gallery.id %}">{{ gallery.Name }}</a>
						<br>
						<a class="text-dark" href="{% url 'App:profile' gallery.Owner.id %}"><strong>{{ gallery.Owner.get_full_name }}</strong></a>
					</div>
					<div class="dropdown ml-auto">
						<h6 class="m-0" data-toggle="dropdown">
							<i class="fas fa-ellipsis-h"></i>
						</h6>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="{% url 'API:deleteGallery' gallery.id %}">
								Delete Gallery
								<i class="far fa-trash-alt"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
			<a href="{% url 'App:gallery' gallery.id %}">
				<div class="card-body p-0 text-center">
					{% for photo in gallery.photo_set.all %}
						<img style="max-height: 150px; max-width: 150px;" src="{{ photo.url }}" alt="">
					{% endfor %}
				</div>
			</a>
			<div class="card-footer bg-white">
				<div class="row px-2">
					<ul class="d-block p-0 m-0" style="list-style: none">
						{% for comment in gallery.gallerycomment_set.all %}
							<li>
								<a class="text-dark mr-1" href='{% url 'App:profile' comment.User.id %}'><strong>{{ comment.User.get_full_name }}</strong></a>
								<span>{{ comment.Text }}</span>
								{#								<a class="text-dark" href='#'><i class="far fa-edit"></i></a>#}
								<a class="text-dark" href='{% url 'API:deleteComment' comment.id %}'><i class="far fa-trash-alt"></i></a>
							</li>
						{% endfor %}
					</ul>
				</div>
				<hr>
				<div class="row px-2">
					<form class="form-inline w-100" method="get" action="{% url 'API:addGalleryComment' gallery.id %}">
						<div class="input-group w-100">
							<input type="text" name="comment" class="form-control" style="resize: none" aria-label="Add a comment…" placeholder="Add a comment…">
							<div class="input-group-append">
								<button class="btn btn-outline-dark input-group-text" type="submit">
									<i class="far fa-comment"></i>
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

WebService/templates/Shared/photoCard.html
<a name="{{ photo.UUID }}"></a>
<div class="navbar-placeholder"></div>
<div class="container align-content-center">
	<div class="col-xl-6 col-lg-8 col-md-10 mx-auto">
		<div class="card">
			<div class="card-header bg-white">
				<div class="row align-items-center px-2">
					<a class="" href="">
						<img class="" style="height: 36px; width: 36px; border-radius: 100%"
						     src="{{ user.profile.ProfilePhoto.url }}"
						     alt="">
					</a>
					<div class="ml-2">
						<a class="m-0 text-dark" href="{% url 'App:profile' photo.Gallery.Owner.id %}"><strong>{{ photo.Gallery.Owner.get_full_name }}</strong></a>
						<br>
						<a class="text-dark" href="#">{{ photo.Location }}</a>
					</div>
					<div class="dropdown ml-auto">
						<h6 class="m-0" data-toggle="dropdown">
							<i class="fas fa-ellipsis-h"></i>
						</h6>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="{% url 'API:deletePhoto' %}?id={{ photo.id }}">
								Delete Image
								<i class="far fa-trash-alt"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="card-body p-0">
				<a href="{% url 'App:gallery' photo.Gallery.id %}#{{ photo.UUID }}">
					<img class="card-img" src="{{ photo.url }}" alt="">
				</a>
			</div>
			<div class="card-footer bg-white">
				<div class="row align-items-center px-2">
					<a class="text-dark mr-3" onclick="likePhoto({{ photo.id }})">
						{#					<a class="text-dark mr-3" href="{% url 'API:likePhoto' photo.id %}">#}
						<h4>
							<i id="heart{{ photo.id }}" class="far fa-heart"></i>
							{# Todo: Change icon when pressed#}
							{# <i class="fas fa-heart"></i>#}
						</h4>
					</a>
					<a class="text-dark" href="#">
						<h4>
							<i class="far fa-comment"></i>
						</h4>
					</a>
					<a class="ml-auto text-dark" href="#">
						<h4>
							<i class="far fa-bookmark"></i>
							{# Todo: Change icon when pressed#}
							{#								<i class="fas fa-bookmark"></i>#}
						</h4>
					</a>
				</div>
				<div class="row px-2">
					<a class="text-dark mr-2" href="#">
						<strong id="likesCounter{{ photo.id }}">{{ photo.like_set.count }}</strong><strong> likes</strong>
					</a>
				</div>
				<div class="row px-2">
					{% if photo.Description %}
						<a class="text-dark mr-1" href='{% url 'App:profile' photo.Gallery.Owner.id %}'><strong>{{ photo.Gallery.Owner.get_full_name }}</strong></a>
						<span>{{ photo.Description }}</span>
					{% endif %}
				</div>
				{#				<div class="row px-2">#}
				{#					<a class="text-secondary mr-2" href="#">View all 22 comments</a>#}
				{#				</div>#}
				<div class="row px-2">
					<ul class="d-block p-0 m-0" style="list-style: none">
						{% for comment in photo.photocomment_set.all %}
							<li>
								<a class="text-dark mr-1" href='{% url 'App:profile' comment.User.id %}'><strong>{{ comment.User.get_full_name }}</strong></a>
								<span>{{ comment.Text }}</span>
								{#								<a class="text-dark" href='#'><i class="far fa-edit"></i></a>#}
								<a class="text-dark" href='{% url 'API:deleteComment' comment.id %}'><i class="far fa-trash-alt"></i></a>
							</li>
						{% endfor %}
					</ul>
				</div>
				<div class="row px-2">
					<a class="text-secondary mr-2" href="#">
						<time datetime="{{ photo.UploadDateTime }}">{{ photo.UploadDateTime }}</time>
					</a>
				</div>
				<hr>
				<div class="row px-2">
					<form class="form-inline w-100" method="get" action="{% url 'API:addComment' photo.id %}">
						<div class="input-group w-100">
							<input type="text" name="comment" class="form-control" style="resize: none" aria-label="Add a comment…" placeholder="Add a comment…">
							<div class="input-group-append">
								<button class="btn btn-outline-dark input-group-text" type="submit">
									<i class="far fa-comment"></i>
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>