WebService/API/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('status/', views.statusView, name='status'),
	path('status/<str:node>/', views.nodeStatusView, name='nodeStatus'),
	path('addComment/<int:photoId>', views.addComment, name='addComment'),
	path('addGalleryComment/<int:galleryId>', views.addGalleryComment, name='addGalleryComment'),
	path('deleteComment/<int:commentId>/', views.deleteComment, name='deleteComment'),
	path('uploadPhoto/', views.uploadPhoto, name='uploadPhoto'),
	path('uploadProfilePhoto/', views.uploadProfilePhoto, name='uploadProfilePhoto'),
	path('makeFriendship/<int:friendId>/', views.makeFriendship, name='makeFriendship'),
	path('deleteFriendship/<int:friendId>/', views.deleteFriendship, name='deleteFriendship'),
	path('login', views.loginExternal, name='login'),
	path('register', views.registerExternal, name='register'),
	path('likePhoto/<int:photoId>/', views.likePhoto, name='likePhoto'),
	path('deletePhoto', views.deletePhoto, name='deletePhoto'),
	path('deleteGallery/<int:galleryId>/', views.deleteGallery, name='deleteGallery'),
	path('profile', views.profile, name='profile'),
	path('gallery', views.gallery, name='gallery'),
	path('homeFeed', views.homeFeed, name='homeFeed'),
	path('galleryFeed', views.galleryFeed, name='galleryFeed'),
]

WebService/App/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.dynamicHomeView, name='home'),
	path('staticHome', views.homeView, name='staticHome'),
	path('profile/<int:id>/', views.profileView, name='profile'),
	path('myProfile/', views.myProfileView, name='myProfile'),
	path('gallery/<int:id>/', views.galleryView, name='gallery'),
	path('uploadPhoto/', views.uploadPhotoView, name='uploadPhoto'),
	path('uploadProfilePhoto/', views.uploadProfilePhotoView, name='uploadProfilePhoto'),
	path('listOfUsers/', views.listOfUsers, name='listOfUsers'),
	path('login/', views.loginView, name='login'),
	path('register/', views.registerView, name='register'),
	path('logout/', views.logoutView, name='logout'),
	path('createGallery/', views.createGallery, name='createGallery'),
]

WebService/WebService/urls.py
from django.contrib import admin
from django.urls import path, include

from WebService.zoo import zk

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include(('App.urls', 'App'), namespace='App')),
	path('api/', include(('API.urls', 'API'), namespace='API')),
]
zk.initialize()

WebService/templates/Base/Footer.html
<div class="navbar-placeholder"></div>
{#<footer>#}
{#	<div class="container">#}
{#		<p class="text-center m-0">#}
{#			Copyright © 2018 TUClery.#}
{#		</p>#}
{#	</div>#}
{#</footer>#}

WebService/templates/Base/HeadLinks.html
{% load static %}
<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

{#	Bootstrap#}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
{#<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>#}
<script src="{% static 'js/bootstrap.min.js' %}"></script>

{#<script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>#}
<script src="{% static 'js/vue.js' %}"></script>

{#	Fontawesome #}
<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}"/>

{#	Google Fonts#}
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&amp;subset=greek" rel="stylesheet">

{#<link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}"/>#}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?version=1.2"/>

WebService/templates/Base/HeadMeta.html
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
{#	<title>Page Title. Maximum length 60-70 characters</title>#}
<meta name="title" content="TUClery">
<meta name="application-name" content="TUClery">

{#	<meta name="description" content="Page description. No longer than 155 characters."/>#}
<meta name="author" content="TUClery">
<meta name="description" content="TUClery">
<meta name="keywords" content="TUClery">
<meta name="theme-color" content="#5AF">
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<link rel="icon" href="{% static 'images/favicon.ico' %}"/>

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="mask-icon" href="{% static '/images/Logo.png' %}" color="#5AF" sizes="any">

{#	<!-- Apple Mobile -->#}
<meta name="apple-mobile-web-app-title" content="TUClery">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="apple-touch-icon" href="{% static '/images/Logo.png' %}">
<link rel="apple-touch-icon-precomposed" href="{% static '/images/Logo.png' %}">

{#-------------------------------------------------------------------------------#}
{#	<!-- Schema.org markup for Google+ -->#}
<meta itemprop="name" content="TUClery">
<meta itemprop="description" content="TUClery">
<meta itemprop="image" content="{% static 'images/Logo.png' %}">

{#	<!-- Twitter Card data -->#}
<meta name="twitter:card" content="{% static 'images/Logo.png' %}">
<meta name="twitter:site" content="TUClery">
<meta name="twitter:title" content="TUClery">
{#	<meta name="twitter:description" content="Page description less than 200 characters">#}
<meta name="twitter:description" content="TUClery">
<meta name="twitter:creator" content="TUClery">
{#	<!-- Twitter summary card with large image must be at least 280x150px -->#}
<meta name="twitter:image:src" content="{% static 'images/Logo.png' %}">
<meta name="twitter:image:alt" content="TUClery">


{#	<!-- Open Graph data -->#}
<meta property="og:title" content="TUClery"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="#"/>
<meta property="og:image" content="{% static 'images/Logo.png' %}"/>
<meta property="og:description" content="TUClery"/>
<meta property="og:site_name" content="TUClery"/>
{#	<meta property="article:published_time" content="2013-09-17T05:59:00+01:00"/>#}
{#	<meta property="article:modified_time" content="2013-09-16T19:08:47+01:00"/>#}
{#	<meta property="article:section" content="Article Section"/>#}
{#	<meta property="article:tag" content="Article Tag"/>#}
{#	<meta property="fb:admins" content="TUClery"/>#}
{#	<meta property="fb:app_id" content="TUClery"/>#}

WebService/templates/Base/NavigationBar.html
{% load static %}
<nav class="navbar fixed-top navbar-expand navbar-light bg-white border-bottom">
	<div class="container">
		<a class="navbar-brand" href="{% url 'App:home' %}">
			{#			<img src="{% static 'images/Logo.svg' %}" alt="TUClery Logo" height="30">#}
			TUClery
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<form class="form-inline ml-auto">
				<div class="input-group">
					<input class="form-control" type="search" placeholder="Search" aria-label="Search">
					<div class="input-group-append">
						<button class="btn btn-outline-dark" type="submit">
							<i class="fas fa-search"></i>
						</button>
					</div>
				</div>
			</form>
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link" href="#"><i class="far fa-compass"></i></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#"><i class="far fa-heart"></i></a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="far fa-user"></i>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
						<a class="dropdown-item" href="{% url 'App:myProfile' %}"><i class="far fa-user-circle"></i> Profile</a>
						<a class="dropdown-item" href="{% url 'App:logout' %}"><i class="fas fa-sign-out-alt"></i> Log out</a>
					</div>
				</li>
			</ul>
		</div>
	</div>
</nav>

WebService/templates/Base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}TUClery</title>
	{% include 'Base/HeadMeta.html' %}
	{% include 'Base/HeadLinks.html' %}
</head>
<body>
<div class="loader-bg">
	<div class="loader">
		<div></div>
		<div></div>
	</div>
</div>

{% include 'Base/NavigationBar.html' %}
{#<div style="min-height: 100vh; margin-bottom: -75px">#}
{% block body %}{% endblock %}
{#</div>#}
{% include 'Base/Footer.html' %}
</body>
<script type="text/javascript">
	$(window).on('load', function () {
		$(".loader-bg").fadeOut('slow');
	});
</script>
{# Basic Logic #}
<script src="{% static 'js/main.js' %}"></script>
</html>