WebService/API/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('status/', views.statusView, name='status'),
	path('status/<str:node>/', views.nodeStatusView, name='nodeStatus'),
	path('addComment/<int:photoId>', views.addComment, name='addComment'),
	path('addGalleryComment/<int:galleryId>', views.addGalleryComment, name='addGalleryComment'),
	path('deleteComment/<int:commentId>/', views.deleteComment, name='deleteComment'),
	path('uploadPhoto/', views.uploadPhoto, name='uploadPhoto'),
	path('uploadProfilePhoto/', views.uploadProfilePhoto, name='uploadProfilePhoto'),
	path('makeFriendship/<int:friendId>/', views.makeFriendship, name='makeFriendship'),
	path('deleteFriendship/<int:friendId>/', views.deleteFriendship, name='deleteFriendship'),
	path('login', views.loginExternal, name='login'),
	path('register', views.registerExternal, name='register'),
	path('likePhoto/<int:photoId>/', views.likePhoto, name='likePhoto'),
	path('deletePhoto', views.deletePhoto, name='deletePhoto'),
	path('deleteGallery/<int:galleryId>/', views.deleteGallery, name='deleteGallery'),
	path('profile', views.profile, name='profile'),
	path('gallery', views.gallery, name='gallery'),
	path('homeFeed', views.homeFeed, name='homeFeed'),
	path('galleryFeed', views.galleryFeed, name='galleryFeed'),
]

WebService/App/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.dynamicHomeView, name='home'),
	path('staticHome', views.homeView, name='staticHome'),
	path('profile/<int:id>/', views.profileView, name='profile'),
	path('myProfile/', views.myProfileView, name='myProfile'),
	path('gallery/<int:id>/', views.galleryView, name='gallery'),
	path('uploadPhoto/', views.uploadPhotoView, name='uploadPhoto'),
	path('uploadProfilePhoto/', views.uploadProfilePhotoView, name='uploadProfilePhoto'),
	path('listOfUsers/', views.listOfUsers, name='listOfUsers'),
	path('login/', views.loginView, name='login'),
	path('register/', views.registerView, name='register'),
	path('logout/', views.logoutView, name='logout'),
	path('createGallery/', views.createGallery, name='createGallery'),
]

WebService/WebService/urls.py
from django.contrib import admin
from django.urls import path, include

from WebService.zoo import zk

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include(('App.urls', 'App'), namespace='App')),
	path('api/', include(('API.urls', 'API'), namespace='API')),
]
zk.initialize()

WebService/App/models.py
import json
import requests
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from WebService.cryptography import cr
from WebService.zoo import zk


class Gallery(models.Model):
	Owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
	Name = models.CharField(max_length=100)

	def __str__(self): return str(self.Name) + " - " + str(self.Owner)


class Photo(models.Model):
	Gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, default=1, null=True, blank=True)
	UploadDateTime = models.DateTimeField(auto_now_add=True, null=True)
	UUID = models.CharField(max_length=1024)
	Location = models.CharField(default='', blank=True, null=True, max_length=100)
	Description = models.CharField(default='', blank=True, null=True, max_length=1024)

	def __str__(self): return str(self.Gallery) + " - " + self.UUID

	@property
	def url(self):
		try:
			requestUrl = zk.applicationService + 'getStorageService/' + self.UUID + '/'
			response = requests.get(requestUrl)
			content = json.loads(response.text)
			try:
				username = self.Gallery.Owner.username
			except Exception:
				username = ""
			sharedKeyBase64 = ''
			for storageService in zk.storageServicesList:
				if storageService['url'] == content['storageService']:
					sharedKeyBase64 = storageService['sharedKey']
					break
			hmac = cr.defaultEncrypt(inputData=self.UUID + username, sharedKeyBase64=sharedKeyBase64)['data']
			url = content['storageService'] + 'getImage?uuid=' + self.UUID + '&username=' + username + '&hmac=' + hmac
			return url
		except Exception:
			return ""


class Profile(models.Model):
	User = models.OneToOneField(User, on_delete=models.CASCADE)
	AuthService = models.CharField(max_length=100, blank=True, default='')
	AuthServiceUserId = models.PositiveIntegerField(blank=True, default=1)
	ProfilePhoto = models.ForeignKey(Photo, on_delete=models.SET_DEFAULT, default=None, null=True, blank=True)

	@property
	def FullName(self): return self.User.first_name + ' ' + self.User.last_name

	def __str__(self): return self.FullName

	@property
	def photoUrl(self):
		try:
			requestUrl = zk.applicationService + 'getStorageService/' + self.PhotoUUID + '/'
			response = requests.get(requestUrl)
			content = json.loads(response.text)
			return content['storageService'] + 'getImage/' + self.PhotoUUID + '/'
		except Exception:
			return ""


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(User=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()


class Friendship(models.Model):
	User = models.ForeignKey('auth.User', default=1, on_delete=models.CASCADE, related_name='User')
	Friend = models.ForeignKey('auth.User', default=1, on_delete=models.CASCADE, related_name='Friend')

	def __str__(self): return str(self.User) + " -> " + str(self.Friend)


class GalleryComment(models.Model):
	User = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
	Gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, default=1)
	UploadDateTime = models.DateTimeField(default=None, null=True)
	Text = models.CharField(max_length=1024)

	def __str__(self): return str(self.Gallery) + " - " + str(self.UploadDateTime)


class PhotoComment(models.Model):
	User = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
	Photo = models.ForeignKey(Photo, on_delete=models.CASCADE, default=1)
	UploadDateTime = models.DateTimeField(auto_now_add=True, null=True)
	Text = models.CharField(max_length=1024)

	def __str__(self): return str(self.Photo) + " - " + str(self.UploadDateTime)


class Like(models.Model):
	User = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
	Photo = models.ForeignKey(Photo, on_delete=models.CASCADE, default=1)

	def __str__(self): return str(User) + " - " + str(Photo)

WebService/templates/App/createGallery.html
{% extends 'Base/base.html' %}
{% block title %}Create Gallery - {% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	<div class="navbar-placeholder"></div>
	<div class="container">
		<div class="col-4 offset-4">
			<form action="{% url 'App:createGallery' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<input type="text" name="name" class="form-control mb-2" aria-label="Gallery Name…" placeholder="Gallery Name…">
				<button class="btn mx-auto w-100"><i class="fas fa-upload text-center"></i></button>
			</form>
		</div>
	</div>
{% endblock %}

WebService/templates/App/dynamicHome.html
{% extends 'Base/base.html' %}
{% block title %}{% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	<div id="photoList">
		<div v-for="photo in photoList">
			{% include 'Shared/dynamicPhotoCard.html' %}
		</div>
	</div>
{% endblock %}

WebService/templates/App/gallery.html
{% extends 'Base/base.html' %}
{% block title %}{% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	{#	<div class="container mb-2">#}
	{#		<div class="col-4">#}
	{#			<div class="custom-file">#}
	{#				<input type="file" class="custom-file-input" id="customFile">#}
	{#				<label class="custom-file-label" for="customFile">Choose photo</label>#}
	{#			</div>#}
	{#		</div>#}
	{#	</div>#}
	<div class="container h-100">
		<div class="row justify-content-center align-items-center" style="height: 200px">
			<div class="col">
				<h3 class="text-center ">{{ gallery.Name }}</h3>
				<hr class="hr-black">
				<h5 class="text-center">
					<a class="m-0 text-dark" href="{% url 'App:profile' gallery.Owner.id %}">
						<strong>{{ gallery.Owner.get_full_name }}</strong>
					</a>
				</h5>
			</div>
		</div>
	</div>
	{#	{% for photo in gallery.photo_set.all|dictsortreversed:'UploadDateTime' %}#}
	{#		{% include 'Shared/photoCard.html' %}#}
	{#	{% endfor %}#}
	<div id="photoList">
		<div v-for="photo in photoList">
			{% include 'Shared/dynamicPhotoCard.html' %}
		</div>
	</div>
{% endblock %}

WebService/templates/App/home.html
{% extends 'Base/base.html' %}
{% block title %}{% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	<div class="navbar-placeholder"></div>
	{% for photo in photos %}
		{% include 'Shared/photoCard.html' %}
	{% endfor %}
	{#	<div class="container">#}
	{#		<ul>#}
	{#			{% for user in users %}#}
	{#				<li>#}
	{#					<a href="{% url 'App:profile' user.id %}">{{ user.FullName }}</a>#}
	{#				</li>#}
	{#			{% endfor %}#}
	{#		</ul>#}
	{#	</div>#}
{% endblock %}

WebService/templates/App/login.html
{% extends 'Base/base.html' %}
{% block title %}Login{% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	<div class="container mt-5" style="height: 100vh">
		<div class="col-md-6 mx-auto">
			<div class="card">
				<div class="card-header">
					<h1 class="card-title text-center">Login</h1>
				</div>
				<div class="card-body">
					<form action="" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="form-control mb-2" aria-label="Username" placeholder="Username">
						<input type="password" name="password" class="form-control mb-2" aria-label="Password" placeholder="Password">
						<button class="btn btn-outline-success w-100 mb-2" type="submit">Login</button>
						<a class="btn w-100" href="{% url 'App:register' %}">Register</a>
					</form>
				</div>
				{% if authServices %}
					<div class="card-footer text-center">
						<h6 class="text-secondary mb-3">or try logging in with</h6>
						{% for authService in authServices %}
							<a
									class="btn btn-outline-dark mb-2"
									href="{{ authService.loginUrl }}{{ serverUrl }}{% url 'API:login' %}"
									role="button"
									aria-pressed="true"
							>
								{{ authService.name }}
							</a>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

WebService/templates/App/profile.html
{% extends 'Base/base.html' %}
{% block title %}Profile - {% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	<div class="navbar-placeholder"></div>
	<div class="container">
		<div class="row mb-5">
			<div class="col-4">
				<a class="" href="{% url 'App:uploadProfilePhoto' %}">
					{% if user.profile.ProfilePhoto.url %}
						<img class="" style="height: 150px; width: 150px; border-radius: 100%"
						     src="{{ user.profile.ProfilePhoto.url }}"
						     alt="">
					{% else %}
						<div class="text-center" style="height:150px; width:150px; border-radius: 100%; border: 1px solid black">
							<span class="far fa-user text-dark align-self-center" style="font-size: 100px"></span>
						</div>
					{% endif %}
				</a>
			</div>
			<div class="col-8">
				<h1>
					{{ user.get_full_name }}
				</h1>
				{% if isFriend %}
					<h5>
						<a class="text-dark" href="{% url 'App:listOfUsers' %}">
							<i class="fas fa-user-friends"></i>
							Friend List
						</a>
					</h5>
					<h5>
						<a class="text-dark" href="{% url 'App:createGallery' %}">
							<i class="fas fa-book"></i>
							Create Gallery
						</a>
					</h5>
					<h5>
						<a class="text-dark" href="{% url 'App:uploadPhoto' %}">
							<i class="fas fa-upload"></i>
							Upload Photo
						</a>
					</h5>
				{% endif %}
			</div>
		</div>
	</div>
	<hr>
	{% for gallery in user.gallery_set.all %}
		{% include 'Shared/galleryCard.html' %}
	{% endfor %}
{% endblock %}

WebService/templates/App/register.html
{% extends 'Base/base.html' %}
{% block title %}Register{% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	<div class="container mt-5" style="height: 100vh">
		<div class="col-md-6 mx-auto">
			<div class="card">
				<div class="card-header">
					<h1 class="card-title text-center">Register</h1>
				</div>
				<div class="card-body">
					<form action="" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="form-control mb-2" aria-label="Username" placeholder="Username">
						<input type="text" name="firstname" class="form-control mb-2" aria-label="First Name" placeholder="First Name">
						<input type="text" name="lastname" class="form-control mb-2" aria-label="Last Name" placeholder="Last Name">
						<input type="email" name="email" class="form-control mb-2" aria-label="Email" placeholder="Email">
						<input type="password" name="password" class="form-control mb-2" aria-label="Password" placeholder="Password">
						<button class="btn btn-outline-success w-100 mb-2" type="submit">Register</button>
						<a class="btn w-100" href="{% url 'App:login' %}">Login</a>
					</form>
				</div>
				{% if authServices %}
					<div class="card-footer text-center">
						<h6 class="text-secondary mb-3">or try registering with</h6>
						{% for authService in authServices %}
							<a
									class="btn btn-outline-dark mb-2"
									href="{{ authService.registerUrl }}{{ serverUrl }}{% url 'API:register' %}"
									role="button"
									aria-pressed="true"
							>
								{{ authService.name }}
							</a>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

WebService/templates/App/uploadPhoto.html
{% extends 'Base/base.html' %}
{% block title %}Upload photo - {% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	<div class="navbar-placeholder"></div>
	<div class="container">
		<div class="col-4 offset-4">
			<form action="{% url 'API:uploadPhoto' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<select name="galleryId" class="custom-select mb-2">
					<option selected>Select a gallery</option>
					{% for gallery in galleries %}
						<option value="{{ gallery.id }}">{{ gallery.Name }}</option>
					{% endfor %}
				</select>
				<input type="file" name="photoFile" class="file-upload mb-2">
				<input type="text" name="Description" class="form-control mb-2" aria-label="Description…" placeholder="Description…">
				<input type="text" name="Location" class="form-control mb-2" aria-label="Location…" placeholder="Location…">
				<button class="btn mx-auto w-100"><i class="fas fa-upload text-center"></i></button>
			</form>
		</div>
	</div>
{% endblock %}

WebService/templates/App/uploadProfilePhoto.html
{% extends 'Base/base.html' %}
{% block title %}Upload photo - {% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	<div class="navbar-placeholder"></div>
	<div class="container">
		<div class="col-4 offset-4">
			<form action="{% url 'API:uploadProfilePhoto' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<input type="file" name="photoFile" class="file-upload mb-2">
				<button class="btn mx-auto w-100"><i class="fas fa-upload text-center"></i></button>
			</form>
		</div>
	</div>
{% endblock %}

WebService/templates/App/userList.html
{% extends 'Base/base.html' %}
{% block title %}User List - {% endblock %}
{% block body %}
	<div class="navbar-placeholder"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<h1>Others</h1>
				<ul>
					{% for user in unknownUsers %}
						<li>
							<a href="{% url 'App:profile' user.id %}">{{ user.FullName }}</a>
							<a href="{% url 'API:makeFriendship' user.id %}"><i class="far fa-plus-square"></i></a>
						</li>
					{% endfor %}
				</ul>
			</div>
			<div class="col-md-6">
				<h1>Friends</h1>
				<ul>
					{% for user in knownUsers %}
						<li>
							<a href="{% url 'App:profile' user.Friend_id %}">{{ user.Friend.get_full_name }}</a>
							<a href="{% url 'API:deleteFriendship' user.Friend_id %}"><i class="far fa-minus-square"></i></a>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
{% endblock %}